import './tabelaHorario.css'

export default function TabelaHorario() {
    return (
        <div className="tabela-container">
            <table>
                <thead>
                    <tr>
                        <th>Segunda</th>
                        <th>Terça</th>
                        <th>Quarta</th>
                        <th>Quinta</th>
                        <th>Sexta</th>
                        <th>Sábado</th>
                        <th>Domingo</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>07:00</td>
                        <td>07:00</td>
                        <td>07:00</td>
                        <td>07:00</td>
                        <td>07:00</td>
                        <td>07:00</td>
                        <td>07:00</td>
                    </tr>
                    <tr>
                        <td>08:00</td>
                        <td>08:00</td>
                        <td>08:00</td>
                        <td>08:00</td>
                        <td>08:00</td>
                        <td>08:00</td>
                        <td>08:00</td>
                    </tr>
                    <tr>
                        <td>09:00</td>
                        <td>09:00</td>
                        <td>09:00</td>
                        <td>09:00</td>
                        <td>09:00</td>
                        <td>09:00</td>
                        <td>09:00</td>
                    </tr>
                    <tr>
                        <td>10:00</td>
                        <td>10:00</td>
                        <td>10:00</td>
                        <td>10:00</td>
                        <td>10:00</td>
                        <td>10:00</td>
                        <td>10:00</td>
                    </tr>
                    <tr>
                        <td>11:00</td>
                        <td>11:00</td>
                        <td>11:00</td>
                        <td>11:00</td>
                        <td>11:00</td>
                        <td>11:00</td>
                        <td>11:00</td>
                    </tr>
                </tbody>
            </table>
        </div>
    );
}