import "./tabelaHorario.css";

export default function TabelaHorario() {
  return (
    <>
      <table>
        <thead>
          <tr>
            <th>segunda</th>
            <th>terça</th>
            <th>quarta</th>
            <th>quinta</th>
            <th>sexta</th>
            <th>sábado</th>
            <th>domingo</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
          </tr>
          <tr>
            <td>08:00</td>
            <td>08:00</td>
            <td>08:00</td>
            <td>08:00</td>
            <td>08:00</td>
            <td>08:00</td>
            <td>08:00</td>
          </tr>
          <tr>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
            <td>07:00</td>
          </tr>
          <tr>
            <td>09:00</td>
            <td>09:00</td>
            <td>09:00</td>
            <td>09:00</td>
            <td>09:00</td>
            <td>09:00</td>
            <td>09:00</td>
          </tr>
          <tr>
            <td>10:00</td>
            <td>10:00</td>
            <td>10:00</td>
            <td>10:00</td>
            <td>10:00</td>
            <td>10:00</td>
            <td>10:00</td>
          </tr>
        </tbody>
      </table>
    </>
  );
}